twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        'daily-files/text-templates': 'text-templates'

when@test:
    twig:
        strict_variables: true
